# .github/workflows/gitflow_valider_pr.yml

name: "Validation du PR sur main ou develop"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  gitflow_on_pr_main_or_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Validation du PR
        id: valider_pr
        #uses: MCN-CQEN/ceai-cqen-scripts-lib/actions/gitflow/validate-pr
        uses: MCN-CQEN/ceai-cqen-scripts-lib/actions/gitflow/validate-pr@feature/actions-gitflow
        # FIXME : ⚠️ Ce lien ne fonctionnera pas tant que la PR ne sera pas mergée : en attendant, utiliser le lien MCN-CQEN/ceai-cqen-scripts-lib/tree/feature/actions-gitflow/actions/gitflow/validate-pr
        with:
          nom_branche_dest: ${{ github.base_ref }}
          nom_branche_source: ${{ github.head_ref }}